export const BRAZIL_BANKS = [
  { code: "001", name: "Banco do Brasil S.A." },
  { code: "003", name: "Banco da Amazônia S.A." },
  { code: "004", name: "Banco do Nordeste do Brasil S.A." },
  { code: "021", name: "Banestes S.A. - Banco do Estado do Espírito Santo" },
  { code: "025", name: "Banco Alfa S.A." },
  { code: "033", name: "Banco Santander (Brasil) S.A." },
  { code: "037", name: "Banco do Estado do Pará S.A. (Banpará)" },
  { code: "041", name: "Banco do Estado do Rio Grande do Sul S.A. (Banrisul)" },
  { code: "047", name: "Banco do Estado de Sergipe S.A. (Banese)" },
  { code: "070", name: "Banco de Brasília S.A. (BRB)" },
  { code: "077", name: "Banco Inter S.A." },
  { code: "085", name: "Cooperativa Central Ailos" },
  { code: "102", name: "XP Investimentos S.A." },
  { code: "104", name: "Caixa Econômica Federal" },
  { code: "136", name: "UNICRED do Brasil" },
  { code: "184", name: "Itaú BBA S.A." },
  { code: "197", name: "Stone Pagamentos S.A." },
  { code: "208", name: "BTG Pactual S.A." },
  { code: "212", name: "Banco Original S.A." },
  { code: "213", name: "Banco Arbi S.A." },
  { code: "218", name: "Banco BS2 S.A." },
  { code: "224", name: "Banco Fibra S.A." },
  { code: "237", name: "Banco Bradesco S.A." },
  { code: "241", name: "Banco Clássico S.A." },
  { code: "246", name: "Banco ABC Brasil S.A." },
  { code: "260", name: "Nu Pagamentos S.A. (Nubank)" },
  { code: "265", name: "Banco Fator S.A." },
  { code: "290", name: "PagSeguro Internet S.A." },
  { code: "300", name: "Banco de La Nación Argentina" },
  { code: "318", name: "Banco BMG S.A." },
  { code: "323", name: "Mercado Pago - Mercado Crédito" },
  { code: "336", name: "Banco C6 S.A." },
  { code: "341", name: "Itaú Unibanco S.A." },
  { code: "366", name: "Banco Société Générale Brasil S.A." },
  { code: "380", name: "PicPay Serviços S.A." },
  { code: "394", name: "Bradesco Financiamentos S.A." },
  { code: "412", name: "Banco Capital S.A." },
  { code: "422", name: "Banco Safra S.A." },
  { code: "456", name: "Banco MUFG Brasil S.A." },
  { code: "464", name: "Sumitomo Mitsui Banking Corporation Brasil S.A." },
  { code: "473", name: "Banco Caixa Geral Brasil S.A." },
  { code: "487", name: "Deutsche Bank S.A. - Banco Alemão" },
  { code: "488", name: "JPMorgan Chase Bank, National Association" },
  { code: "492", name: "ING Bank N.V." },
  { code: "494", name: "Banco de La República Oriental del Uruguay" },
  { code: "495", name: "Banco de La Provincia de Buenos Aires" },
  { code: "505", name: "Banco Credit Suisse (Brasil) S.A." },
  { code: "600", name: "Banco Luso Brasileiro S.A." },
  { code: "604", name: "Banco Industrial do Brasil S.A." },
  { code: "610", name: "Banco VR S.A." },
  { code: "611", name: "Banco Paulista S.A." },
  { code: "612", name: "Banco Guanabara S.A." },
  { code: "613", name: "Banco Omni S.A." },
  { code: "623", name: "Banco PAN S.A." },
  { code: "626", name: "Banco Ficsa S.A." },
  { code: "630", name: "Banco Intercap S.A." },
  { code: "633", name: "Banco Rendimento S.A." },
  { code: "634", name: "Banco Triângulo S.A. (Tribanco)" },
  { code: "637", name: "Banco Sofisa S.A." },
  { code: "641", name: "Banco Alvorada S.A." },
  { code: "643", name: "Banco Pine S.A." },
  { code: "652", name: "Itaú Unibanco Holding S.A." },
  { code: "653", name: "Banco Voiter S.A. (ex-Indusval)" },
  { code: "654", name: "Banco A.J. Renner S.A." },
  { code: "655", name: "Banco Votorantim S.A. (BV)" },
  { code: "707", name: "Banco Daycoval S.A." },
  { code: "712", name: "Banco Ourinvest S.A." },
  { code: "739", name: "Banco Cetelem S.A." },
  { code: "741", name: "Banco Ribeirão Preto S.A." },
  { code: "743", name: "Banco Semear S.A." },
  { code: "745", name: "Banco Citibank S.A." },
  { code: "746", name: "Banco Modal S.A." },
  { code: "747", name: "Banco Rabobank International Brasil S.A." },
  { code: "748", name: "Sicredi - Banco Cooperativo Sicredi S.A." },
  { code: "751", name: "Scotiabank Brasil S.A. Banco Múltiplo" },
  { code: "752", name: "BNP Paribas Brasil S.A." },
  { code: "755", name: "Bank of America Merrill Lynch Banco Múltiplo S.A." },
  { code: "756", name: "Sicoob - Banco Cooperativo do Brasil S.A." },
  { code: "OUTRO", name: "Outro banco (preencher manualmente)" }
];